// Generates src/generated/version.ts with the current build id + timestamp.
// Run automatically via the `prebuild` npm script before every build.
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
let buildId = 'dev';
try {
  buildId = execSync('git rev-parse --short HEAD', { cwd: root, encoding: 'utf-8' }).trim();
} catch {
  const d = new Date();
  const p2 = (n) => String(n).padStart(2, '0');
  buildId = `${d.getFullYear()}${p2(d.getMonth() + 1)}${p2(d.getDate())}-${p2(d.getHours())}${p2(d.getMinutes())}`;
}
const buildTime = new Date().toISOString();

mkdirSync(join(root, 'src', 'generated'), { recursive: true });
writeFileSync(
  join(root, 'src', 'generated', 'version.ts'),
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit.\nexport const BUILD_ID = ${JSON.stringify(buildId)};\nexport const BUILD_TIME = ${JSON.stringify(buildTime)};\n`
);
console.log(`version.ts -> BUILD_ID=${buildId}`);
